FROM python:3.13.0-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV VIRTUAL_ENV=/venv
ENV UV_PROJECT_ENVIRONMENT=/venv
ENV PATH="/venv/bin:$PATH"
ENV PYTHONPATH="/app"

RUN pip install --no-cache-dir uv && \
    uv venv -q /venv

WORKDIR /app

COPY lungo/pyproject.toml lungo/uv.lock ./
RUN uv sync --locked --no-dev --no-editable

COPY lungo/ .
